namespace ZapretUI
{
    partial class Main
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Header = new Bunifu.UI.WinForms.BunifuPanel();
            bt_gitea = new Bunifu.UI.WinForms.BunifuImageButton();
            bt_github = new Bunifu.UI.WinForms.BunifuImageButton();
            label1 = new Label();
            bt_boosty = new Bunifu.UI.WinForms.BunifuImageButton();
            bt_Minimize = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            bt_appClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            bunifuFormDrag1 = new Bunifu.UI.WinForms.BunifuFormDrag();
            bt_installer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            bt_start = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            bt_stop = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            bt_settings = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            bunifuProgressBar1 = new Bunifu.UI.WinForms.BunifuProgressBar();
            bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            Header.SuspendLayout();
            bunifuGroupBox1.SuspendLayout();
            SuspendLayout();
            // 
            // Header
            // 
            Header.BackgroundColor = Color.FromArgb(30, 30, 30);
            Header.BackgroundImage = (Image)resources.GetObject("Header.BackgroundImage");
            Header.BackgroundImageLayout = ImageLayout.Stretch;
            Header.BorderColor = Color.FromArgb(30, 30, 30);
            Header.BorderRadius = 0;
            Header.BorderThickness = 0;
            Header.Controls.Add(bt_gitea);
            Header.Controls.Add(bt_github);
            Header.Controls.Add(label1);
            Header.Controls.Add(bt_boosty);
            Header.Controls.Add(bt_Minimize);
            Header.Controls.Add(bt_appClose);
            Header.Dock = DockStyle.Top;
            Header.ForeColor = Color.White;
            Header.Location = new Point(0, 0);
            Header.Name = "Header";
            Header.ShowBorders = true;
            Header.Size = new Size(345, 30);
            Header.TabIndex = 1;
            // 
            // bt_gitea
            // 
            bt_gitea.ActiveImage = null;
            bt_gitea.AllowAnimations = true;
            bt_gitea.AllowBuffering = false;
            bt_gitea.AllowToggling = false;
            bt_gitea.AllowZooming = true;
            bt_gitea.AllowZoomingOnFocus = false;
            bt_gitea.BackColor = Color.FromArgb(30, 30, 30);
            bt_gitea.DialogResult = DialogResult.None;
            bt_gitea.Dock = DockStyle.Right;
            bt_gitea.ErrorImage = (Image)resources.GetObject("bt_gitea.ErrorImage");
            bt_gitea.FadeWhenInactive = false;
            bt_gitea.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            bt_gitea.Image = (Image)resources.GetObject("bt_gitea.Image");
            bt_gitea.ImageActive = null;
            bt_gitea.ImageLocation = null;
            bt_gitea.ImageMargin = 5;
            bt_gitea.ImageSize = new Size(38, 25);
            bt_gitea.ImageZoomSize = new Size(43, 30);
            bt_gitea.InitialImage = (Image)resources.GetObject("bt_gitea.InitialImage");
            bt_gitea.Location = new Point(134, 0);
            bt_gitea.Name = "bt_gitea";
            bt_gitea.Rotation = 0;
            bt_gitea.ShowActiveImage = true;
            bt_gitea.ShowCursorChanges = true;
            bt_gitea.ShowImageBorders = true;
            bt_gitea.ShowSizeMarkers = false;
            bt_gitea.Size = new Size(43, 30);
            bt_gitea.TabIndex = 9;
            bt_gitea.ToolTipText = "";
            bt_gitea.WaitOnLoad = false;
            bt_gitea.Zoom = 5;
            bt_gitea.ZoomSpeed = 10;
            bt_gitea.Click += bt_gitea_Click;
            // 
            // bt_github
            // 
            bt_github.ActiveImage = null;
            bt_github.AllowAnimations = true;
            bt_github.AllowBuffering = false;
            bt_github.AllowToggling = false;
            bt_github.AllowZooming = true;
            bt_github.AllowZoomingOnFocus = false;
            bt_github.BackColor = Color.FromArgb(30, 30, 30);
            bt_github.DialogResult = DialogResult.None;
            bt_github.Dock = DockStyle.Right;
            bt_github.ErrorImage = (Image)resources.GetObject("bt_github.ErrorImage");
            bt_github.FadeWhenInactive = false;
            bt_github.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            bt_github.Image = (Image)resources.GetObject("bt_github.Image");
            bt_github.ImageActive = null;
            bt_github.ImageLocation = null;
            bt_github.ImageMargin = 5;
            bt_github.ImageSize = new Size(25, 25);
            bt_github.ImageZoomSize = new Size(30, 30);
            bt_github.InitialImage = (Image)resources.GetObject("bt_github.InitialImage");
            bt_github.Location = new Point(177, 0);
            bt_github.Name = "bt_github";
            bt_github.Rotation = 0;
            bt_github.ShowActiveImage = true;
            bt_github.ShowCursorChanges = true;
            bt_github.ShowImageBorders = true;
            bt_github.ShowSizeMarkers = false;
            bt_github.Size = new Size(30, 30);
            bt_github.TabIndex = 8;
            bt_github.ToolTipText = "";
            bt_github.WaitOnLoad = false;
            bt_github.Zoom = 5;
            bt_github.ZoomSpeed = 10;
            bt_github.Click += bt_github_Click;
            // 
            // label1
            // 
            label1.BackColor = Color.Transparent;
            label1.Dock = DockStyle.Left;
            label1.Font = new Font("Segoe UI", 10F);
            label1.ForeColor = Color.White;
            label1.Location = new Point(0, 0);
            label1.Name = "label1";
            label1.Size = new Size(66, 30);
            label1.TabIndex = 7;
            label1.Text = "ZapretUI";
            label1.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // bt_boosty
            // 
            bt_boosty.ActiveImage = null;
            bt_boosty.AllowAnimations = true;
            bt_boosty.AllowBuffering = false;
            bt_boosty.AllowToggling = false;
            bt_boosty.AllowZooming = true;
            bt_boosty.AllowZoomingOnFocus = false;
            bt_boosty.BackColor = Color.FromArgb(30, 30, 30);
            bt_boosty.DialogResult = DialogResult.None;
            bt_boosty.Dock = DockStyle.Right;
            bt_boosty.ErrorImage = (Image)resources.GetObject("bt_boosty.ErrorImage");
            bt_boosty.FadeWhenInactive = false;
            bt_boosty.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            bt_boosty.Image = (Image)resources.GetObject("bt_boosty.Image");
            bt_boosty.ImageActive = null;
            bt_boosty.ImageLocation = null;
            bt_boosty.ImageMargin = 5;
            bt_boosty.ImageSize = new Size(25, 25);
            bt_boosty.ImageZoomSize = new Size(30, 30);
            bt_boosty.InitialImage = (Image)resources.GetObject("bt_boosty.InitialImage");
            bt_boosty.Location = new Point(207, 0);
            bt_boosty.Name = "bt_boosty";
            bt_boosty.Rotation = 0;
            bt_boosty.ShowActiveImage = true;
            bt_boosty.ShowCursorChanges = true;
            bt_boosty.ShowImageBorders = true;
            bt_boosty.ShowSizeMarkers = false;
            bt_boosty.Size = new Size(30, 30);
            bt_boosty.TabIndex = 6;
            bt_boosty.ToolTipText = "";
            bt_boosty.WaitOnLoad = false;
            bt_boosty.Zoom = 5;
            bt_boosty.ZoomSpeed = 10;
            bt_boosty.Click += bt_boosty_Click;
            // 
            // bt_Minimize
            // 
            bt_Minimize.AllowAnimations = true;
            bt_Minimize.AllowMouseEffects = true;
            bt_Minimize.AllowToggling = false;
            bt_Minimize.AnimationSpeed = 200;
            bt_Minimize.AutoGenerateColors = false;
            bt_Minimize.AutoRoundBorders = false;
            bt_Minimize.AutoSizeLeftIcon = true;
            bt_Minimize.AutoSizeRightIcon = true;
            bt_Minimize.BackColor = Color.Transparent;
            bt_Minimize.BackColor1 = Color.FromArgb(60, 60, 60);
            bt_Minimize.BackgroundImage = (Image)resources.GetObject("bt_Minimize.BackgroundImage");
            bt_Minimize.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_Minimize.ButtonText = "_";
            bt_Minimize.ButtonTextMarginLeft = 0;
            bt_Minimize.ColorContrastOnClick = 45;
            bt_Minimize.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            bt_Minimize.CustomizableEdges = borderEdges1;
            bt_Minimize.DialogResult = DialogResult.None;
            bt_Minimize.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bt_Minimize.DisabledFillColor = Color.Empty;
            bt_Minimize.DisabledForecolor = Color.Empty;
            bt_Minimize.Dock = DockStyle.Right;
            bt_Minimize.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bt_Minimize.Font = new Font("Segoe UI", 9F);
            bt_Minimize.ForeColor = Color.White;
            bt_Minimize.IconLeft = null;
            bt_Minimize.IconLeftAlign = ContentAlignment.MiddleLeft;
            bt_Minimize.IconLeftCursor = Cursors.Default;
            bt_Minimize.IconLeftPadding = new Padding(11, 3, 3, 3);
            bt_Minimize.IconMarginLeft = 11;
            bt_Minimize.IconPadding = 10;
            bt_Minimize.IconRight = null;
            bt_Minimize.IconRightAlign = ContentAlignment.MiddleRight;
            bt_Minimize.IconRightCursor = Cursors.Default;
            bt_Minimize.IconRightPadding = new Padding(3, 3, 7, 3);
            bt_Minimize.IconSize = 25;
            bt_Minimize.IdleBorderColor = Color.Empty;
            bt_Minimize.IdleBorderRadius = 0;
            bt_Minimize.IdleBorderThickness = 0;
            bt_Minimize.IdleFillColor = Color.Empty;
            bt_Minimize.IdleIconLeftImage = null;
            bt_Minimize.IdleIconRightImage = null;
            bt_Minimize.IndicateFocus = false;
            bt_Minimize.Location = new Point(237, 0);
            bt_Minimize.Name = "bt_Minimize";
            bt_Minimize.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bt_Minimize.OnDisabledState.BorderRadius = 6;
            bt_Minimize.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_Minimize.OnDisabledState.BorderThickness = 0;
            bt_Minimize.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bt_Minimize.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bt_Minimize.OnDisabledState.IconLeftImage = null;
            bt_Minimize.OnDisabledState.IconRightImage = null;
            bt_Minimize.onHoverState.BorderColor = Color.Transparent;
            bt_Minimize.onHoverState.BorderRadius = 6;
            bt_Minimize.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_Minimize.onHoverState.BorderThickness = 0;
            bt_Minimize.onHoverState.FillColor = Color.Gray;
            bt_Minimize.onHoverState.ForeColor = Color.White;
            bt_Minimize.onHoverState.IconLeftImage = null;
            bt_Minimize.onHoverState.IconRightImage = null;
            bt_Minimize.OnIdleState.BorderColor = Color.Transparent;
            bt_Minimize.OnIdleState.BorderRadius = 6;
            bt_Minimize.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_Minimize.OnIdleState.BorderThickness = 0;
            bt_Minimize.OnIdleState.FillColor = Color.FromArgb(60, 60, 60);
            bt_Minimize.OnIdleState.ForeColor = Color.White;
            bt_Minimize.OnIdleState.IconLeftImage = null;
            bt_Minimize.OnIdleState.IconRightImage = null;
            bt_Minimize.OnPressedState.BorderColor = Color.Transparent;
            bt_Minimize.OnPressedState.BorderRadius = 6;
            bt_Minimize.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_Minimize.OnPressedState.BorderThickness = 0;
            bt_Minimize.OnPressedState.FillColor = Color.FromArgb(80, 80, 80);
            bt_Minimize.OnPressedState.ForeColor = Color.White;
            bt_Minimize.OnPressedState.IconLeftImage = null;
            bt_Minimize.OnPressedState.IconRightImage = null;
            bt_Minimize.Size = new Size(54, 30);
            bt_Minimize.TabIndex = 5;
            bt_Minimize.TabStop = false;
            bt_Minimize.TextAlign = ContentAlignment.MiddleCenter;
            bt_Minimize.TextAlignment = HorizontalAlignment.Center;
            bt_Minimize.TextMarginLeft = 0;
            bt_Minimize.TextPadding = new Padding(0);
            bt_Minimize.UseDefaultRadiusAndThickness = true;
            bt_Minimize.Click += _Minimize_Click;
            // 
            // bt_appClose
            // 
            bt_appClose.AllowAnimations = true;
            bt_appClose.AllowMouseEffects = true;
            bt_appClose.AllowToggling = false;
            bt_appClose.AnimationSpeed = 200;
            bt_appClose.AutoGenerateColors = false;
            bt_appClose.AutoRoundBorders = false;
            bt_appClose.AutoSizeLeftIcon = true;
            bt_appClose.AutoSizeRightIcon = true;
            bt_appClose.BackColor = Color.Transparent;
            bt_appClose.BackColor1 = Color.FromArgb(60, 60, 60);
            bt_appClose.BackgroundImage = (Image)resources.GetObject("bt_appClose.BackgroundImage");
            bt_appClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_appClose.ButtonText = "X";
            bt_appClose.ButtonTextMarginLeft = 0;
            bt_appClose.ColorContrastOnClick = 45;
            bt_appClose.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            bt_appClose.CustomizableEdges = borderEdges2;
            bt_appClose.DialogResult = DialogResult.None;
            bt_appClose.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bt_appClose.DisabledFillColor = Color.Empty;
            bt_appClose.DisabledForecolor = Color.Empty;
            bt_appClose.Dock = DockStyle.Right;
            bt_appClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bt_appClose.Font = new Font("Segoe UI", 9F);
            bt_appClose.ForeColor = Color.White;
            bt_appClose.IconLeft = null;
            bt_appClose.IconLeftAlign = ContentAlignment.MiddleLeft;
            bt_appClose.IconLeftCursor = Cursors.Default;
            bt_appClose.IconLeftPadding = new Padding(11, 3, 3, 3);
            bt_appClose.IconMarginLeft = 11;
            bt_appClose.IconPadding = 10;
            bt_appClose.IconRight = null;
            bt_appClose.IconRightAlign = ContentAlignment.MiddleRight;
            bt_appClose.IconRightCursor = Cursors.Default;
            bt_appClose.IconRightPadding = new Padding(3, 3, 7, 3);
            bt_appClose.IconSize = 25;
            bt_appClose.IdleBorderColor = Color.Empty;
            bt_appClose.IdleBorderRadius = 0;
            bt_appClose.IdleBorderThickness = 0;
            bt_appClose.IdleFillColor = Color.Empty;
            bt_appClose.IdleIconLeftImage = null;
            bt_appClose.IdleIconRightImage = null;
            bt_appClose.IndicateFocus = false;
            bt_appClose.Location = new Point(291, 0);
            bt_appClose.Name = "bt_appClose";
            bt_appClose.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bt_appClose.OnDisabledState.BorderRadius = 6;
            bt_appClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_appClose.OnDisabledState.BorderThickness = 0;
            bt_appClose.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bt_appClose.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bt_appClose.OnDisabledState.IconLeftImage = null;
            bt_appClose.OnDisabledState.IconRightImage = null;
            bt_appClose.onHoverState.BorderColor = Color.Transparent;
            bt_appClose.onHoverState.BorderRadius = 6;
            bt_appClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_appClose.onHoverState.BorderThickness = 0;
            bt_appClose.onHoverState.FillColor = Color.FromArgb(192, 0, 0);
            bt_appClose.onHoverState.ForeColor = Color.White;
            bt_appClose.onHoverState.IconLeftImage = null;
            bt_appClose.onHoverState.IconRightImage = null;
            bt_appClose.OnIdleState.BorderColor = Color.Transparent;
            bt_appClose.OnIdleState.BorderRadius = 6;
            bt_appClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_appClose.OnIdleState.BorderThickness = 0;
            bt_appClose.OnIdleState.FillColor = Color.FromArgb(60, 60, 60);
            bt_appClose.OnIdleState.ForeColor = Color.White;
            bt_appClose.OnIdleState.IconLeftImage = null;
            bt_appClose.OnIdleState.IconRightImage = null;
            bt_appClose.OnPressedState.BorderColor = Color.Transparent;
            bt_appClose.OnPressedState.BorderRadius = 6;
            bt_appClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_appClose.OnPressedState.BorderThickness = 0;
            bt_appClose.OnPressedState.FillColor = Color.FromArgb(200, 50, 50);
            bt_appClose.OnPressedState.ForeColor = Color.White;
            bt_appClose.OnPressedState.IconLeftImage = null;
            bt_appClose.OnPressedState.IconRightImage = null;
            bt_appClose.Size = new Size(54, 30);
            bt_appClose.TabIndex = 3;
            bt_appClose.TabStop = false;
            bt_appClose.TextAlign = ContentAlignment.MiddleCenter;
            bt_appClose.TextAlignment = HorizontalAlignment.Center;
            bt_appClose.TextMarginLeft = 0;
            bt_appClose.TextPadding = new Padding(0);
            bt_appClose.UseDefaultRadiusAndThickness = true;
            bt_appClose.Click += _appClose_Click;
            // 
            // bunifuFormDrag1
            // 
            bunifuFormDrag1.AllowOpacityChangesWhileDragging = true;
            bunifuFormDrag1.ContainerControl = this;
            bunifuFormDrag1.DockIndicatorsOpacity = 0.5D;
            bunifuFormDrag1.DockingIndicatorsColor = Color.FromArgb(202, 215, 233);
            bunifuFormDrag1.DockingOptions.DockAll = true;
            bunifuFormDrag1.DockingOptions.DockBottomLeft = true;
            bunifuFormDrag1.DockingOptions.DockBottomRight = true;
            bunifuFormDrag1.DockingOptions.DockFullScreen = true;
            bunifuFormDrag1.DockingOptions.DockLeft = true;
            bunifuFormDrag1.DockingOptions.DockRight = true;
            bunifuFormDrag1.DockingOptions.DockTopLeft = true;
            bunifuFormDrag1.DockingOptions.DockTopRight = true;
            bunifuFormDrag1.DragOpacity = 0.9D;
            bunifuFormDrag1.Enabled = false;
            bunifuFormDrag1.ParentForm = this;
            bunifuFormDrag1.ShowCursorChanges = true;
            bunifuFormDrag1.ShowDockingIndicators = true;
            bunifuFormDrag1.TitleBarOptions.BunifuFormDrag = bunifuFormDrag1;
            bunifuFormDrag1.TitleBarOptions.DoubleClickToExpandWindow = false;
            bunifuFormDrag1.TitleBarOptions.Enabled = true;
            bunifuFormDrag1.TitleBarOptions.TitleBarControl = Header;
            bunifuFormDrag1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bt_installer
            // 
            bt_installer.AllowAnimations = true;
            bt_installer.AllowMouseEffects = true;
            bt_installer.AllowToggling = false;
            bt_installer.AnimationSpeed = 200;
            bt_installer.AutoGenerateColors = false;
            bt_installer.AutoRoundBorders = false;
            bt_installer.AutoSizeLeftIcon = true;
            bt_installer.AutoSizeRightIcon = true;
            bt_installer.BackColor = Color.Transparent;
            bt_installer.BackColor1 = Color.FromArgb(51, 122, 183);
            bt_installer.BackgroundImage = (Image)resources.GetObject("bt_installer.BackgroundImage");
            bt_installer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_installer.ButtonText = "Установка";
            bt_installer.ButtonTextMarginLeft = 0;
            bt_installer.ColorContrastOnClick = 45;
            bt_installer.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            bt_installer.CustomizableEdges = borderEdges6;
            bt_installer.DialogResult = DialogResult.None;
            bt_installer.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bt_installer.DisabledFillColor = Color.Empty;
            bt_installer.DisabledForecolor = Color.Empty;
            bt_installer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bt_installer.Font = new Font("Segoe UI", 9F);
            bt_installer.ForeColor = Color.White;
            bt_installer.IconLeft = null;
            bt_installer.IconLeftAlign = ContentAlignment.MiddleLeft;
            bt_installer.IconLeftCursor = Cursors.Default;
            bt_installer.IconLeftPadding = new Padding(11, 3, 3, 3);
            bt_installer.IconMarginLeft = 11;
            bt_installer.IconPadding = 10;
            bt_installer.IconRight = null;
            bt_installer.IconRightAlign = ContentAlignment.MiddleRight;
            bt_installer.IconRightCursor = Cursors.Default;
            bt_installer.IconRightPadding = new Padding(3, 3, 7, 3);
            bt_installer.IconSize = 25;
            bt_installer.IdleBorderColor = Color.Empty;
            bt_installer.IdleBorderRadius = 0;
            bt_installer.IdleBorderThickness = 0;
            bt_installer.IdleFillColor = Color.Empty;
            bt_installer.IdleIconLeftImage = null;
            bt_installer.IdleIconRightImage = null;
            bt_installer.IndicateFocus = false;
            bt_installer.Location = new Point(18, 111);
            bt_installer.Name = "bt_installer";
            bt_installer.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bt_installer.OnDisabledState.BorderRadius = 1;
            bt_installer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_installer.OnDisabledState.BorderThickness = 1;
            bt_installer.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bt_installer.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bt_installer.OnDisabledState.IconLeftImage = null;
            bt_installer.OnDisabledState.IconRightImage = null;
            bt_installer.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
            bt_installer.onHoverState.BorderRadius = 1;
            bt_installer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_installer.onHoverState.BorderThickness = 1;
            bt_installer.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
            bt_installer.onHoverState.ForeColor = Color.White;
            bt_installer.onHoverState.IconLeftImage = null;
            bt_installer.onHoverState.IconRightImage = null;
            bt_installer.OnIdleState.BorderColor = Color.DodgerBlue;
            bt_installer.OnIdleState.BorderRadius = 1;
            bt_installer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_installer.OnIdleState.BorderThickness = 1;
            bt_installer.OnIdleState.FillColor = Color.DodgerBlue;
            bt_installer.OnIdleState.ForeColor = Color.White;
            bt_installer.OnIdleState.IconLeftImage = null;
            bt_installer.OnIdleState.IconRightImage = null;
            bt_installer.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bt_installer.OnPressedState.BorderRadius = 1;
            bt_installer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_installer.OnPressedState.BorderThickness = 1;
            bt_installer.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bt_installer.OnPressedState.ForeColor = Color.White;
            bt_installer.OnPressedState.IconLeftImage = null;
            bt_installer.OnPressedState.IconRightImage = null;
            bt_installer.Size = new Size(150, 39);
            bt_installer.TabIndex = 2;
            bt_installer.TextAlign = ContentAlignment.MiddleCenter;
            bt_installer.TextAlignment = HorizontalAlignment.Center;
            bt_installer.TextMarginLeft = 0;
            bt_installer.TextPadding = new Padding(0);
            bt_installer.UseDefaultRadiusAndThickness = true;
            bt_installer.Click += bt_installer_Click;
            // 
            // bt_start
            // 
            bt_start.AllowAnimations = true;
            bt_start.AllowMouseEffects = true;
            bt_start.AllowToggling = false;
            bt_start.AnimationSpeed = 200;
            bt_start.AutoGenerateColors = false;
            bt_start.AutoRoundBorders = false;
            bt_start.AutoSizeLeftIcon = true;
            bt_start.AutoSizeRightIcon = true;
            bt_start.BackColor = Color.Transparent;
            bt_start.BackColor1 = Color.FromArgb(51, 122, 183);
            bt_start.BackgroundImage = (Image)resources.GetObject("bt_start.BackgroundImage");
            bt_start.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_start.ButtonText = "Запуск";
            bt_start.ButtonTextMarginLeft = 0;
            bt_start.ColorContrastOnClick = 45;
            bt_start.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            bt_start.CustomizableEdges = borderEdges4;
            bt_start.DialogResult = DialogResult.None;
            bt_start.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bt_start.DisabledFillColor = Color.Empty;
            bt_start.DisabledForecolor = Color.Empty;
            bt_start.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bt_start.Font = new Font("Segoe UI", 9F);
            bt_start.ForeColor = Color.White;
            bt_start.IconLeft = null;
            bt_start.IconLeftAlign = ContentAlignment.MiddleLeft;
            bt_start.IconLeftCursor = Cursors.Default;
            bt_start.IconLeftPadding = new Padding(11, 3, 3, 3);
            bt_start.IconMarginLeft = 11;
            bt_start.IconPadding = 10;
            bt_start.IconRight = null;
            bt_start.IconRightAlign = ContentAlignment.MiddleRight;
            bt_start.IconRightCursor = Cursors.Default;
            bt_start.IconRightPadding = new Padding(3, 3, 7, 3);
            bt_start.IconSize = 25;
            bt_start.IdleBorderColor = Color.Empty;
            bt_start.IdleBorderRadius = 0;
            bt_start.IdleBorderThickness = 0;
            bt_start.IdleFillColor = Color.Empty;
            bt_start.IdleIconLeftImage = null;
            bt_start.IdleIconRightImage = null;
            bt_start.IndicateFocus = false;
            bt_start.Location = new Point(6, 22);
            bt_start.Name = "bt_start";
            bt_start.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bt_start.OnDisabledState.BorderRadius = 1;
            bt_start.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_start.OnDisabledState.BorderThickness = 1;
            bt_start.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bt_start.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bt_start.OnDisabledState.IconLeftImage = null;
            bt_start.OnDisabledState.IconRightImage = null;
            bt_start.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
            bt_start.onHoverState.BorderRadius = 1;
            bt_start.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_start.onHoverState.BorderThickness = 1;
            bt_start.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
            bt_start.onHoverState.ForeColor = Color.White;
            bt_start.onHoverState.IconLeftImage = null;
            bt_start.onHoverState.IconRightImage = null;
            bt_start.OnIdleState.BorderColor = Color.DodgerBlue;
            bt_start.OnIdleState.BorderRadius = 1;
            bt_start.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_start.OnIdleState.BorderThickness = 1;
            bt_start.OnIdleState.FillColor = Color.DodgerBlue;
            bt_start.OnIdleState.ForeColor = Color.White;
            bt_start.OnIdleState.IconLeftImage = null;
            bt_start.OnIdleState.IconRightImage = null;
            bt_start.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bt_start.OnPressedState.BorderRadius = 1;
            bt_start.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_start.OnPressedState.BorderThickness = 1;
            bt_start.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bt_start.OnPressedState.ForeColor = Color.White;
            bt_start.OnPressedState.IconLeftImage = null;
            bt_start.OnPressedState.IconRightImage = null;
            bt_start.Size = new Size(150, 39);
            bt_start.TabIndex = 3;
            bt_start.TextAlign = ContentAlignment.MiddleCenter;
            bt_start.TextAlignment = HorizontalAlignment.Center;
            bt_start.TextMarginLeft = 0;
            bt_start.TextPadding = new Padding(0);
            bt_start.UseDefaultRadiusAndThickness = true;
            bt_start.Click += bt_start_Click;
            // 
            // bt_stop
            // 
            bt_stop.AllowAnimations = true;
            bt_stop.AllowMouseEffects = true;
            bt_stop.AllowToggling = false;
            bt_stop.AnimationSpeed = 200;
            bt_stop.AutoGenerateColors = false;
            bt_stop.AutoRoundBorders = false;
            bt_stop.AutoSizeLeftIcon = true;
            bt_stop.AutoSizeRightIcon = true;
            bt_stop.BackColor = Color.Transparent;
            bt_stop.BackColor1 = Color.FromArgb(51, 122, 183);
            bt_stop.BackgroundImage = (Image)resources.GetObject("bt_stop.BackgroundImage");
            bt_stop.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_stop.ButtonText = "Остановка";
            bt_stop.ButtonTextMarginLeft = 0;
            bt_stop.ColorContrastOnClick = 45;
            bt_stop.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            bt_stop.CustomizableEdges = borderEdges3;
            bt_stop.DialogResult = DialogResult.None;
            bt_stop.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bt_stop.DisabledFillColor = Color.Empty;
            bt_stop.DisabledForecolor = Color.Empty;
            bt_stop.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bt_stop.Font = new Font("Segoe UI", 9F);
            bt_stop.ForeColor = Color.White;
            bt_stop.IconLeft = null;
            bt_stop.IconLeftAlign = ContentAlignment.MiddleLeft;
            bt_stop.IconLeftCursor = Cursors.Default;
            bt_stop.IconLeftPadding = new Padding(11, 3, 3, 3);
            bt_stop.IconMarginLeft = 11;
            bt_stop.IconPadding = 10;
            bt_stop.IconRight = null;
            bt_stop.IconRightAlign = ContentAlignment.MiddleRight;
            bt_stop.IconRightCursor = Cursors.Default;
            bt_stop.IconRightPadding = new Padding(3, 3, 7, 3);
            bt_stop.IconSize = 25;
            bt_stop.IdleBorderColor = Color.Empty;
            bt_stop.IdleBorderRadius = 0;
            bt_stop.IdleBorderThickness = 0;
            bt_stop.IdleFillColor = Color.Empty;
            bt_stop.IdleIconLeftImage = null;
            bt_stop.IdleIconRightImage = null;
            bt_stop.IndicateFocus = false;
            bt_stop.Location = new Point(162, 22);
            bt_stop.Name = "bt_stop";
            bt_stop.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bt_stop.OnDisabledState.BorderRadius = 1;
            bt_stop.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_stop.OnDisabledState.BorderThickness = 1;
            bt_stop.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bt_stop.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bt_stop.OnDisabledState.IconLeftImage = null;
            bt_stop.OnDisabledState.IconRightImage = null;
            bt_stop.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
            bt_stop.onHoverState.BorderRadius = 1;
            bt_stop.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_stop.onHoverState.BorderThickness = 1;
            bt_stop.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
            bt_stop.onHoverState.ForeColor = Color.White;
            bt_stop.onHoverState.IconLeftImage = null;
            bt_stop.onHoverState.IconRightImage = null;
            bt_stop.OnIdleState.BorderColor = Color.DodgerBlue;
            bt_stop.OnIdleState.BorderRadius = 1;
            bt_stop.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_stop.OnIdleState.BorderThickness = 1;
            bt_stop.OnIdleState.FillColor = Color.DodgerBlue;
            bt_stop.OnIdleState.ForeColor = Color.White;
            bt_stop.OnIdleState.IconLeftImage = null;
            bt_stop.OnIdleState.IconRightImage = null;
            bt_stop.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bt_stop.OnPressedState.BorderRadius = 1;
            bt_stop.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_stop.OnPressedState.BorderThickness = 1;
            bt_stop.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bt_stop.OnPressedState.ForeColor = Color.White;
            bt_stop.OnPressedState.IconLeftImage = null;
            bt_stop.OnPressedState.IconRightImage = null;
            bt_stop.Size = new Size(150, 39);
            bt_stop.TabIndex = 4;
            bt_stop.TextAlign = ContentAlignment.MiddleCenter;
            bt_stop.TextAlignment = HorizontalAlignment.Center;
            bt_stop.TextMarginLeft = 0;
            bt_stop.TextPadding = new Padding(0);
            bt_stop.UseDefaultRadiusAndThickness = true;
            bt_stop.Click += bt_stop_Click;
            // 
            // bt_settings
            // 
            bt_settings.AllowAnimations = true;
            bt_settings.AllowMouseEffects = true;
            bt_settings.AllowToggling = false;
            bt_settings.AnimationSpeed = 200;
            bt_settings.AutoGenerateColors = false;
            bt_settings.AutoRoundBorders = false;
            bt_settings.AutoSizeLeftIcon = true;
            bt_settings.AutoSizeRightIcon = true;
            bt_settings.BackColor = Color.Transparent;
            bt_settings.BackColor1 = Color.FromArgb(51, 122, 183);
            bt_settings.BackgroundImage = (Image)resources.GetObject("bt_settings.BackgroundImage");
            bt_settings.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_settings.ButtonText = "Настройки";
            bt_settings.ButtonTextMarginLeft = 0;
            bt_settings.ColorContrastOnClick = 45;
            bt_settings.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            bt_settings.CustomizableEdges = borderEdges5;
            bt_settings.DialogResult = DialogResult.None;
            bt_settings.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bt_settings.DisabledFillColor = Color.Empty;
            bt_settings.DisabledForecolor = Color.Empty;
            bt_settings.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bt_settings.Font = new Font("Segoe UI", 9F);
            bt_settings.ForeColor = Color.White;
            bt_settings.IconLeft = null;
            bt_settings.IconLeftAlign = ContentAlignment.MiddleLeft;
            bt_settings.IconLeftCursor = Cursors.Default;
            bt_settings.IconLeftPadding = new Padding(11, 3, 3, 3);
            bt_settings.IconMarginLeft = 11;
            bt_settings.IconPadding = 10;
            bt_settings.IconRight = null;
            bt_settings.IconRightAlign = ContentAlignment.MiddleRight;
            bt_settings.IconRightCursor = Cursors.Default;
            bt_settings.IconRightPadding = new Padding(3, 3, 7, 3);
            bt_settings.IconSize = 25;
            bt_settings.IdleBorderColor = Color.Empty;
            bt_settings.IdleBorderRadius = 0;
            bt_settings.IdleBorderThickness = 0;
            bt_settings.IdleFillColor = Color.Empty;
            bt_settings.IdleIconLeftImage = null;
            bt_settings.IdleIconRightImage = null;
            bt_settings.IndicateFocus = false;
            bt_settings.Location = new Point(179, 111);
            bt_settings.Name = "bt_settings";
            bt_settings.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bt_settings.OnDisabledState.BorderRadius = 1;
            bt_settings.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_settings.OnDisabledState.BorderThickness = 1;
            bt_settings.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bt_settings.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bt_settings.OnDisabledState.IconLeftImage = null;
            bt_settings.OnDisabledState.IconRightImage = null;
            bt_settings.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
            bt_settings.onHoverState.BorderRadius = 1;
            bt_settings.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_settings.onHoverState.BorderThickness = 1;
            bt_settings.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
            bt_settings.onHoverState.ForeColor = Color.White;
            bt_settings.onHoverState.IconLeftImage = null;
            bt_settings.onHoverState.IconRightImage = null;
            bt_settings.OnIdleState.BorderColor = Color.DodgerBlue;
            bt_settings.OnIdleState.BorderRadius = 1;
            bt_settings.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_settings.OnIdleState.BorderThickness = 1;
            bt_settings.OnIdleState.FillColor = Color.DodgerBlue;
            bt_settings.OnIdleState.ForeColor = Color.White;
            bt_settings.OnIdleState.IconLeftImage = null;
            bt_settings.OnIdleState.IconRightImage = null;
            bt_settings.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bt_settings.OnPressedState.BorderRadius = 1;
            bt_settings.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bt_settings.OnPressedState.BorderThickness = 1;
            bt_settings.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bt_settings.OnPressedState.ForeColor = Color.White;
            bt_settings.OnPressedState.IconLeftImage = null;
            bt_settings.OnPressedState.IconRightImage = null;
            bt_settings.Size = new Size(150, 39);
            bt_settings.TabIndex = 5;
            bt_settings.TextAlign = ContentAlignment.MiddleCenter;
            bt_settings.TextAlignment = HorizontalAlignment.Center;
            bt_settings.TextMarginLeft = 0;
            bt_settings.TextPadding = new Padding(0);
            bt_settings.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuProgressBar1
            // 
            bunifuProgressBar1.AllowAnimations = false;
            bunifuProgressBar1.Animation = 0;
            bunifuProgressBar1.AnimationSpeed = 220;
            bunifuProgressBar1.AnimationStep = 10;
            bunifuProgressBar1.BackColor = Color.FromArgb(223, 223, 223);
            bunifuProgressBar1.BackgroundImage = (Image)resources.GetObject("bunifuProgressBar1.BackgroundImage");
            bunifuProgressBar1.BorderColor = Color.FromArgb(223, 223, 223);
            bunifuProgressBar1.BorderRadius = 9;
            bunifuProgressBar1.BorderThickness = 1;
            bunifuProgressBar1.Dock = DockStyle.Bottom;
            bunifuProgressBar1.Location = new Point(0, 159);
            bunifuProgressBar1.Maximum = 100;
            bunifuProgressBar1.MaximumValue = 100;
            bunifuProgressBar1.Minimum = 0;
            bunifuProgressBar1.MinimumValue = 0;
            bunifuProgressBar1.Name = "bunifuProgressBar1";
            bunifuProgressBar1.Orientation = Orientation.Horizontal;
            bunifuProgressBar1.ProgressBackColor = Color.FromArgb(223, 223, 223);
            bunifuProgressBar1.ProgressColorLeft = Color.DodgerBlue;
            bunifuProgressBar1.ProgressColorRight = Color.DodgerBlue;
            bunifuProgressBar1.Size = new Size(345, 13);
            bunifuProgressBar1.TabIndex = 6;
            bunifuProgressBar1.Value = 0;
            bunifuProgressBar1.ValueByTransition = 0;
            // 
            // bunifuGroupBox1
            // 
            bunifuGroupBox1.BorderColor = Color.LightGray;
            bunifuGroupBox1.BorderRadius = 1;
            bunifuGroupBox1.BorderThickness = 1;
            bunifuGroupBox1.Controls.Add(bt_stop);
            bunifuGroupBox1.Controls.Add(bt_start);
            bunifuGroupBox1.Font = new Font("Segoe UI", 9F);
            bunifuGroupBox1.LabelAlign = HorizontalAlignment.Left;
            bunifuGroupBox1.LabelIndent = 10;
            bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            bunifuGroupBox1.Location = new Point(12, 36);
            bunifuGroupBox1.Name = "bunifuGroupBox1";
            bunifuGroupBox1.Size = new Size(317, 69);
            bunifuGroupBox1.TabIndex = 7;
            bunifuGroupBox1.TabStop = false;
            bunifuGroupBox1.Text = "Состояние";
            // 
            // Main
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(224, 224, 224);
            ClientSize = new Size(345, 172);
            Controls.Add(bunifuGroupBox1);
            Controls.Add(bunifuProgressBar1);
            Controls.Add(bt_settings);
            Controls.Add(bt_installer);
            Controls.Add(Header);
            DoubleBuffered = true;
            ForeColor = Color.Black;
            FormBorderStyle = FormBorderStyle.None;
            Icon = (Icon)resources.GetObject("$this.Icon");
            Name = "Main";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "ZapretUI";
            Load += Form1_Load;
            Header.ResumeLayout(false);
            bunifuGroupBox1.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel Header;
        private Bunifu.UI.WinForms.BunifuFormDrag bunifuFormDrag1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bt_appClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bt_Minimize;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuImageButton bt_boosty;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bt_installer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bt_stop;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bt_start;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bt_settings;
        private Bunifu.UI.WinForms.BunifuProgressBar bunifuProgressBar1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuImageButton bt_gitea;
        private Bunifu.UI.WinForms.BunifuImageButton bt_github;
    }
}
